
version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: db_test
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_SSL_MODE: disable
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"


  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: db_test
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_SSL_MODE: disable
      ENV: ${ENV}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
      AGE_API_URL: ${AGE_API_URL}
      GENDER_API_URL: ${GENDER_API_URL}
      NATIONALITY_API_URL: ${NATIONALITY_API_URL}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres

