
version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"


  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      ENV: ${ENV}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
      AGE_API_URL: ${AGE_API_URL}
      GENDER_API_URL: ${GENDER_API_URL}
      NATIONALITY_API_URL: ${NATIONALITY_API_URL}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
volumes:
  postgres_db:

