
version: '3.9'

services:

  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - .:/build
    networks:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      ENV: ${ENV}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
      AGE_API_URL: ${AGE_API_URL}
      GENDER_API_URL: ${GENDER_API_URL}
      NATIONALITY_API_URL: ${NATIONALITY_API_URL}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - db



  db:
      container_name: postgres_container
      volumes:
        - pgdb:/var/lib/postgresql/data/
      image: postgres
      networks:
        - postgres
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      ports:
       - ${POSTGRES_PORT}:${POSTGRES_PORT}


volumes:
  pgdb:
networks:
  postgres:
    driver: bridge
    name: postgres_net

